### ISSUE TITLE
N64 Compatibility

### ISSUE THREAD

**Issue by austinkelleher** [wenkesj/sn#1]
When can I expect an N64 binary for this repo?

Thanks,

Austin

**Comment by wenkesj** [comment]
I moved this issue to `help wanted` for further inspection. Need input from prospective users.

**Comment by austinkelleher** [comment]
:+1:

**Comment by austinkelleher** [comment]
Looking for a status update on this issue. Thanks.

**Comment by wenkesj** [comment]
# N64 Status

Got eem.

**Comment by austinkelleher** [comment]
Still looking for a status update on this issue. Thanks.

**Comment by austinkelleher** [comment]
Looking for a status update. K. Thx.

**Comment by austinkelleher** [comment]
Closing because bae.

**Comment by wenkesj** [comment]
Reopening because this needs to be improved

**Comment by austinkelleher** [comment]
Spring cleaning issues.
